#!/usr/bin/env sh

set -e

if [ $# -eq 0 ]; then
  echo -e "Please provide the AWS Role ARN to assume. Optionally provide the session name."
  echo -e "\tmaikelmertens/aws-assume-role:latest ROLE_ARN [ROLE_SESSION_NAME]"
  exit 1
fi

AWS_ROLE="${1}"
AWS_SESSION_NAME="${2:-assumerole}"

AWS_ENV_VARS=$(aws sts assume-role \
                --role-arn "${AWS_ROLE}" \
                --role-session-name "${AWS_SESSION_NAME}" \
                --query '[Credentials.AccessKeyId,Credentials.SecretAccessKey,Credentials.SessionToken]' \
                --output text)

echo "export AWS_DEFAULT_REGION=${AWS_REGION:-eu-west-1}"
echo "export AWS_REGION=${AWS_REGION:-eu-west-1}"

echo "export AWS_ACCESS_KEY_ID='${AWS_ENV_VARS[0]}'"
echo "export AWS_SECRET_ACCESS_KEY='${AWS_ENV_VARS[1]}'"

echo "export AWS_SESSION_TOKEN='${AWS_ENV_VARS[2]}'"
echo "export AWS_SECURITY_TOKEN='${AWS_ENV_VARS[2]}'"
echo "export AWS_DELEGATION_TOKEN='${AWS_ENV_VARS[2]}'"
